### ISSUE TITLE
/EXIT on windows to kill GUI after render

### ISSUE THREAD

**Issue by DangerousPrototypes** [libre3d/render-3d#17]
If you append /EXIT to the POV-ray command the GUI won't hang in Windows during development.

**Comment by jonyo** [comment]
@DangerousPrototypes Have you confirmed the library works in a Windows environment, other than that change?  I don't have a WAMP environment to test on at the moment so the most I can do is make sure it doesn't break anything in *nix environments, thought I'm happy to add changes that are confirmed to make it work in Windows or other environments.

Adding `/EXIT` in *nix environment causes an error, so we can't just add it blindly.  Perhaps add it if an option is passed like `$render3d->options(['add_exit' => true])`.  If you submit a PR for something like that I'd be happy to review and possibly merge if it looks good.
