### ISSUE TITLE
strtolower to detect .STL|.stl|etc

### ISSUE THREAD

**Issue by DangerousPrototypes** [libre3d/render-3d#18]
render3d.php ln 171

```
        $this->fileType = strtolower(empty($pathInfo['extension']) ? '' : $pathInfo['extension']);
```

**Comment by jonyo** [comment]
@DangerousPrototypes Something like this I think is outside the scope of the library, it should be done by the app before using the library.  Forcing it to be lowercase in the library would remove some of the flexibility.

For instance, on libre3d.com we sanitize the filename prior to making any calls to this library, and as part of that sanitation we lowercase the extension and make sure it is one of the types that can be rendered.  Only then do we call up the library and attempt to convert / render it.

Hope that helps, if you have any trouble using the library I'm happy to help!

**Comment by DangerousPrototypes** [comment]
Thanks! I just wanted to leave a note for anyone else having issues (or 
warn that it is one). I was unable to process any file with capital .STL 
in extension using the library. It does seem to have a check for .stl or 
.scad that is case sensitive. My frontend determined the file type, gets 
some statistics like volume and bounding box, and then sends to library 
for render. The library always failed with an uppercase file extension 
because of this check.

All user uploads are renamed in base36 and moved to folder above webroot 
so I did some more extensive hacking to get it working for us. If anyone 
is having intermittent problems though, especially with user supplied 
files that are messy, do check for uppercase extensions.

**Comment by jonyo** [comment]
@DangerousPrototypes 

I thought on it more, and I think it could be good to do some sort of file type matching (not a blind `stltolower` though).  A thought I had, was to do a case-insensitive comparison between the file types and the provided file type, and make it match the case of any registered file type it finds.  If the case is different, rename the file to match automatically.  Perhaps have a `strict` option, that if set, it would not do this case matching and would basically fail (for any use cases where someone might not want it to automatically try renaming the file) when you try to do any conversion or render on it.

Maybe "bake it in" to the `filename()` method, maybe expose that specific part of it in a dedicated method like `matchFiletypeCase()` or similar.

Have any thoughts on that?  I just have a feeling this could turn out to be a common pitfall, if that's the case I think it does make sense to account for it built in now.  I don't want to do all the work (at the end of the day this is meant to handle just the converting / rendering for you), but I think this part makes sense to be built in if it's done right.

**Comment by DangerousPrototypes** [comment]
Sure whatever, Your project. I was just driving.by and screaming out the window. Just for.s&g are.you the "real" Jon Foote who regaled me with stories of security theater in NYC at a nice ale bar in lower.east village a few years ago? If not no worries. Just missed bamf this year And miss my friends. 

Cheers,

Ian

**Comment by jonyo** [comment]
@DangerousPrototypes no, i'm the other one.  But all of us Jon Feet totally know each other, we have a meeting once a month, so I totally know just who you are talking about!  He's the one that looks like this right? :trollface:

**Comment by jonyo** [comment]
Any accounting for upper/lowercase extension should be handled outside of the library so that control stays in the hands of the script using this and not the library.
