### ISSUE TITLE
Render failed :( Exception: Could not open STL file, convert failed.

### ISSUE THREAD

**Issue by ynilsiam** [libre3d/render-3d#20]
Below is my code, it gave me the error in the subject. 
Would you please give me some suggestions? 
There is 'example.stl' in 'files' directory.
Thank you.

`\<!DOCTYPE html\>
\<html\>
\<head\>
\<meta charset="utf-8" /\>
\<title\>MOST 3D Customizer !!!\</title\>
\<?php
require 'vendor/autoload.php';
?\>
\</head\>
\<body\>
\<?php
echo "Beginning of file...\<br\>";

$render3d = new \Libre3d\Render3d\Render3d();

echo "Successful initiated class Render3d...\<br\>";

// this is the working directory, where it will put any files used during the render process, as well as the final
// rendered image.
$render3d->workingDir('/files/');

echo "Successful assigned working directory...\<br\>";

// Set paths to the executables on this system
$render3d->executable('openscad', '/usr/bin/openscad');

echo "Successful executable openscad...\<br\>";

$render3d->executable('povray', '/usr/local/bin/povray');

echo "Successful executable povray...\<br\>";

try {
	// This will copy in your starting file into the working DIR if you give the full path to the starting file.
	// This will also set the fileType for you.
	$render3d->filename('/start/example.stl');

	// Render!  This will do all the necessary conversions as long as the render engine (in this
	// case, the default engine, PovRAY) "knows" how to convert the file into a file it can use for rendering.
	// Note that this is a multi-step process that can be further broken down if you need it to.
	$renderedImagePath = $render3d->render('povray');

	echo "Render successful!  Rendered image will be at $renderedImagePath";
} catch (\Exception $e) {
	echo "Render failed :( Exception: ".$e->getMessage()."\<br\>";
}
echo "End of file...\<br\>";
?\>
\</body\>
\</html\>`

**Comment by jonyo** [comment]
@ynilsiam Sorry so late, I'm not sure why but I must have the github notifications set incorrectly for this repo, I didn't get a notification.  So sorry for the late reply, if you are still looking for the answer:

It sounds like the paths may not be set correctly.  You can see what it is attempting to use for the filename by doing `echo 'file used: ' . $render3d->filename() . '<br>';` That should list the absolute path to the file.  If that looks correct, it may be a file permission problem or similar.

If you are still trying to get this working and need more help feel free to re-open.
