### ISSUE TITLE
Only render preview

### ISSUE THREAD

**Issue by Christophvh** [libre3d/render-3d#27]
Hi,

Thanks for the library. Is it possible to only render the sample image and not the pov files? I would like to use this to generate a thumbnail from a 3D model.

**Comment by jonyo** [comment]
Hey @Christophvh sorry for the late reply, I guess I need to check my notification settings on this repo!

The POV files are a part of the process, they are needed to generate the preview image.  Once the image is generated though you can just delete the other files.
